version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  mega-sudoku.cyrhades.fr:
    image: anssi/fcsc2024-misc-mega-sudoku:latest
    ports:
      - ${PORT_SSH}:4000